micronaut:
  application:
    name: service-roaming-prices
  server:
    port: 8080
    environment:
      log-configurations: true

datasources:
  default:
    jdbcUrl: jdbc:mysql://localhost:3106/roaming_prices
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
    schema-generate: NONE


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # Validates the schema instead of dropping/creating it in production


flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration


logging:
  level:
    io.micronaut.data.query: DEBUG