micronaut:
  server:
    port: 8082
  environment:
    active: test

logging:
  level:
    root: DEBUG
    io.micronaut.data: DEBUG
    org.flywaydb: DEBUG

datasources:
  default:
    jdbcUrl: jdbc:mysql://localhost:54541/test_roaming_prices
    username: test_root
    password: test_root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
    maximum-pool-size: 10